#source 'https://github.com/CocoaPods/Specs.git'
#
target "Enesco1.0" do
pod 'DOUAudioStreamer', '0.2.11'
pod 'SDWebImage'
pod 'GVUserDefaults'
pod 'MBProgressHUD'
pod 'Mantle', '1.5.5'
pod 'AFNetworking', '~> 2.0'
pod 'Zhugeio'
end